### ISSUE TITLE
wish PERuntime.getCurrentContext().getChannel() worked in embedded mode

### ISSUE THREAD

**Issue by dlaboss** [IBMStreams/streamsx.topology#126]
In my case I have test code for a parallel split whose validation includes verifying a tuple was processed on the correct parallel channel.  The function of parallel().split() works fine but the validation fails in embedded context because getChannel() returns -1.  There doesn't seem to be any inherent reason why the correct channel # couldn't be returned in this case too.

**Comment by wmarshall484** [comment]
parallel() only works in STANDALONE and DISTRIBUTED contexts, since it uses SPL's @parallel annotation and Streams runtime to perform the parallelism. As such, PERuntime.getCurrentContext().getChannel() will also not work in embedded.

Current state of things:
When running embedded, rather than throw some sort of "parallel can't be used embedded" exception, we simply run everything serially, without parallelism.

Currently adding this to parallel's javadoc.

**Comment by ddebrunner** [comment]
Please don't add to the parallel docs, we will support a different api to such information, so don't want to advertize an "incorrect" approach.

**Comment by ddebrunner** [comment]
Maybe I mis-understood, I just don't want the current way to access getChannel() be documented.

**Comment by wmarshall484** [comment]
I wasn't planning on documenting getChannel(). I planned on adding the following sentence to the parallel javadoc:

*"parallel() cannot currently be used in an EMBEDDED context. Doing so will merely return a non-parallelized TStream."*

**Comment by ddebrunner** [comment]
Somewhat unclear, "cannot be used" but still does something.

parallel() in embedded is treated as a no-op, the flow will execute as though parallel() had no been called?

**Comment by wmarshall484** [comment]
Changed to "*If parallel is invoked when submitting to an embedded context, the flow will execute as though parallel had not been called.*"
