### ISSUE TITLE
Unable to build com.ibm.streamsx.topology.pysamples(1.7.4)

### ISSUE THREAD

**Issue by jchailloux** [IBMStreams/streamsx.topology#1290]
---- SPL Build for project com.ibm.streamsx.topology.pysamples started ---- November 7, 2017 at 2:52:50 PM GMT+1
Building toolkit index
Building main composite: com.ibm.streamsx.topology.pysamples.apps::NoopSample using build configuration: BuildConfig
/opt/ibm/InfoSphere_Streams/4.2.0.0/bin/sc -M com.ibm.streamsx.topology.pysamples.apps::NoopSample --output-directory=output/com.ibm.streamsx.topology.pysamples.apps.NoopSample/BuildConfig --data-directory=data -a --no-toolkit-indexing --no-mixed-mode-preprocessing 
CDISP0411W WARNING: The error output from the opt/.__splpy/common/pyversion3.sh script is: CDISP0358E ERROR: An internal error occurred. The error is: execvp() failed, with error code: 13, meaning: Permission denied. 
.
com.ibm.streamsx.topology.pysamples.positional/Noop/Noop: CDISP0180E ERROR: An error occurred while the operator model was loading. The error is: The following non-zero return code was received from the opt/.__splpy/common/pyversion3.sh script: 1.

---- SPL Build for project com.ibm.streamsx.topology.pysamples completed in 5.881 seconds ----

**Comment by ddebrunner** [comment]
Can you share what you are trying to do and the steps you took to see the error.

**Comment by jchailloux** [comment]
Import SPL sample then choose the topology toolkit and pysamples.

new BuildConfiguration (as there is none) on NoopSample spl sample.

This error comes while building.

**Comment by ddebrunner** [comment]
It looks like the samples were copied without maintaining file permissions.

**Comment by jchailloux** [comment]
Does it comes from the toolkit or my env ?

**Comment by jchailloux** [comment]
cd /home/streamsadmin/workspace/com.ibm.streamsx.topology.pysamples
chmod -R 777 *

It solves the issue.

**Comment by ddebrunner** [comment]
> Does it comes from the toolkit or my env ?

Guess it depends on exactly what you did to import it?
> Import SPL sample then choose the topology toolkit and pysamples.

Did you start from downloading a release or something else?

**Comment by jchailloux** [comment]
The import was done as follow
<img width="324" alt="screen shot 2017-11-07 at 23 15 54" src="https://user-images.githubusercontent.com/7124757/32520823-a754ef64-c411-11e7-8ed5-94cb45798142.png">

For the toolkit here is what I've done

1 - Downloaded the last release on Github(1.7.4).
2 - unzip on my dedicated folder for toolkits.
3 - backup and delete the topology toolkit from the Streams install/toolkit folder

.bashrc
ADDITIONAL_TOOLKITS=/home/streamsadmin/AdditionalToolkits
export STREAMS_SPLPATH=$ADDITIONAL_TOOLKITS:${STREAMS_QSEVM}/toolkits

**Comment by ddebrunner** [comment]
Did you download the source zip or the tar release bundle?

**Comment by jchailloux** [comment]
Tar release bundle

**Comment by markheger** [comment]
@ddebrunner 
Still having errors while import+build of topology sample in StreamsStudio:
---- SPL Build for project com.ibm.streamsx.topology.pysamples started ---- December 1, 2017 at 3:15:17 PM GMT
Building toolkit index
CDISP9209E ERROR: The /home/streamsadmin/workspace/com.ibm.streamsx.topology.pysamples/impl/nl/en_US/TopologySplpyResource.xlf file was not found.
CDISP0786E ERROR: The generation of the TopologySplpyResource resource bucket failed.

---- SPL Build for project com.ibm.streamsx.topology.pysamples completed in 0.38 seconds ----

**Comment by joergboe** [comment]
@jchailloux The import of samples with streams Studio (import -> Sample SPL App ...) imports always the samples from the Streams product and not from the downloaded toolkit.
The only way to import a downloaded example from github is via 'Import -> General -> Existing Project into workspace' . But in this case the sample must to have a .project file.
A) This should be improved.

If the sample is imported with Studio from the product there are 2 cases:
1 In some Streams versions the generated artifacts (spl-python-extract.py) are included in the sample
2 . In some they are not included.
In case 1 the build of the samples should work.
In case 2 the build of the noop and all other spl main composites wil fail.
B) Therefore the toolkit must have a build script that executes the python extraction step (and that depends on the topology toolkit)
C) The is a build.xml file in the 'python' directory but this does not work in the product because it expects the toolkit in a location relative to the build.xml file. This should be improved

**Comment by natashadsilva** [comment]
I am using the QSE and I'm having this same problem, except these are the steps I followed to resolve it:
1. I imported the samples from the toolkit shipped with the product. 
2. Ran the extract script from command line,
3. I was able to compile from command line, but not from Studio until I set the `PYENV_VERSION` environment variable in my Build Config. I didn't have to change file permissions.

So far the documentation references having `PYTHONHOME` but not the `PYENV_VERSION` variable - @ddebrunner  is this a requirement or just a QSE specific issue?

**Comment by ddebrunner** [comment]
@natashadsilva This seems to be a pyenv issue. `PYENV_VERSION` is not a Python environment variable.

**Comment by joergboe** [comment]
That's why I issued the PR #1343.
This PR implements :
- a build.xml in directory samples/python/com.ibm.streamsx.topology.pysamples
- this build.xml calls the extract script and calls the sc to compile the samples.
- the spl project settings are configured to use the 'external bulild' with this build.xml file
- The info.xml of the sample explains the requirement to set the STREAMS_TOPOLOGY_TOOLKIT environment in oder to build the sample.

**Comment by markheger** [comment]
how to build the samples is documented in info.xml, close this issue
