### ISSUE TITLE
Fixes for StreamingAnalyticService.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.topology#1305]
- [x] Javadoc submission parameter indicates it is submission parameters, but isn't it a complete JCO?
- [x] Submission parameter says "may have results added" - need more detail on what this means.
- [x] Needs `@since` 1.8 markers
- [x] Jobs have identifiers, not "numbers"
- [x] Should `buildAndSubmitJob` return a `BigInteger`? (now returns a `Job`)
- [ ] - Remove the `of` factory method that takes a string, this is not a common use case for clients.

**Comment by ddebrunner** [comment]
@wmarshall484

**Comment by johnmac-ibm** [comment]
@ddebrunner 
wrt submission, at present it's an `AppEntity.submission`  (because that's what `AnalyticsStreamsContextService` uses), so I'm not sure what the best way to describe that for the Javadoc is.

Both methods treat `submission` as an input and output parameter: the response from the submit is merged into `submission` as a `submissionResults` member, if they make it that far (ie. if they throw earlier the results won't be there. I'll try to make that clearer in the Javadoc

And I'll update `buildAndSubmitJob` to return `BigInteger`

**Comment by johnmac-ibm** [comment]
In reviewing the Javadoc, I noticed some classes that were `public` that shouldn't be, I'll address that in the PR as well.

**Comment by ddebrunner** [comment]
I'm not sure AppEntity.submission is a publis api, from the public api point of view at least for submit job the parameter needs to be a configruation that is either:
- a JSON object representing a JCO
- a path to a JCO
- a JobConfig instance.

**Comment by ddebrunner** [comment]
Can you try to keep the pr's focused on a single topic, makes reviewing them and accepting them quicker.

**Comment by johnmac-ibm** [comment]
@ddebrunner  As near as I can tell on the old code path, this is what is made public via `StreamsContext<T>.submit(JsonObject)`, which says the object has a `graph` member and an optional `deploy` member.

What it currently uses for `buildAndSubmitJob`, based on the old code, is `graph`, and then looks in `deploy` for a `jobConfigOverlay` member.

For `submitJob` the structure is the same but `graph` is not used, only `deploy` and `jobConfigOverlay`.

I think it makes sense to keep them both using that same level of object, but I can easily change them if you would prefer.

And I'll keep the PRs separate.
