### ISSUE TITLE
Any equivalent of getSubmissionTimeValue()?

### ISSUE THREAD

**Issue by hildrum** [IBMStreams/streamsx.topology#132]
When doing performance measurements, I often make use of `getSubmissionTimeValue` to control the number of parallel channels and the number of iterations of the source operator, and then resubmit the compiled application multiple times.  Is there an equivalent?

**Comment by ddebrunner** [comment]
Yes and no. You can pass the parallel width in from the Java application, eg as command line arguments, which is a type of submission time value. But that will result in a new spl application being compiled each time. If you want to create a bundle and resubmit it with different widths, that's not possible at the moment.

**Comment by dlaboss** [comment]
MQTT (and the SPL adapters) has notions of userID/password and for ssl, {key,Trust}Store and {key,Trust}StorePassword
 
Seems like its time to add some submissionTimeParam mechanism, otherwise a generated .sab will have to end up having to contain the passwords in the clear - or simply obscured.
 
Presumably the generated code will need to end up with something like:
 
stream<...> source = MQTTSource {
    param
        password : getSubmissionTimeValue("com.ibm.streamsx.topology.messaging.mqtt.password");
 
And add something like... ?
 
List<String> submissionParams = new ArrayList<>();
submissionParams.add("com.ibm.streamsx.topology.messaging.mqtt.password", "mySecretPassword");
 
Map<String,Object> config = ...
config.put(ContestProperties.SUBMISSION_PARAMS, submissionParams);
streamsContext.submit(topology, config)
 
Seems like at some point we'd want to make them available via FunctionContext too?
FunctionContext.getSubmissionTimeValue(String name)
FunctionContext.getSubmissionTimeValue(String name, String default)

**Comment by ddebrunner** [comment]
So would we need a new object that could be passed into an operator's parameter map, something like:

`params.put("password", new SubmissionParameter("password"));`

and SubmissionParameter would support different types in some way, e.g. maybe IntSubmissionParameter extends SubmissionParameter.

**Comment by dlaboss** [comment]
pull#165 contains changes to address submission params for SPL op params as above.  It also includes specifying submission time values via StreamsContext.submit(..., config).

**Comment by dlaboss** [comment]
fixed with pull#182. See cist.SPL, cist.Topology.createSubmissionParameter(), and cist.TStream.parallel()
