### ISSUE TITLE
streamsx.runner: --main-composite parameter expects that namespace is used

### ISSUE THREAD

**Issue by markheger** [IBMStreams/streamsx.topology#1486]
python3 $STREAMS_INSTALL/toolkits/com.ibm.streamsx.topology/opt/python/packages/streamsx/scripts/runner.py - --main-composite=Main ...

streamsx/scripts/runner.py", line 68, in _get_spl_app
    ns, name = cmd_args.main_composite.rsplit('::', 1)
ValueError: not enough values to unpack (expected 2, got 1)

Possibly documentation update or change the script to be able to work with Main composites that have no namespace

**Comment by ddebrunner** [comment]
have to document that non-namespace qualified names are not supported (and raise an error).

This is because we actually invoke the main composite in a Topology Python application, and we can't find an non-qualified name from an namespace (we use `_spl`) and we don't support building an application in the default (no) namespace.

**Comment by ddebrunner** [comment]
This could be changed in the future.
