### ISSUE TITLE
How to check "End of File" when using FileStreams.textFileReader(files)

### ISSUE THREAD

**Issue by hqingshuang** [IBMStreams/streamsx.topology#171]
I'm writing WordCount sample with JAVA API, but I don't know how to check if the file is over in the streaming.

Part of the code is:

        Topology topology = new Topology("WordCount");
        TStream<String> files = FileStreams.directoryWatcher(topology, directory);        
        TStream<String> lines = FileStreams.textFileReader(files);
        TStream<CountInfo> cntInfo = lines.multiTransform(
        		new Function<String, Iterable<CountInfo>>() { 
        			private int lc = 0;
        			private int wc = 0;
        			private int cc = 0;
        			
				@Override
        			public Iterable<CountInfo> apply(String line) {
						++lc;
						wc = wc + Arrays.asList(line.split(" ")).size();
						cc = cc + line.length();
						return Arrays.asList(new CountInfo(lc, wc, cc));
        			}
           .......
I need to output the final result for each file, so if there is a mark of EOF in lines streams it will be easy.

In SPL, we will use onPunct and check (currentPunct()==Sys.FinalMarker) as below.
  stream<LineStat> CountAllLines  = Custom(CountOneLine) 
  {
    logic
      state : 
      {
        mutable LineStat aggregate = { lines=0, wcs = {words=0, chars=0} };
      }
      onTuple CountOneLine :
      {  ...   }      
      onPunct CountOneLine:
      {
        if(currentPunct()==Sys.FinalMarker) 
          submit(aggregate, CountAllLines);
      }    
  }

**Comment by ddebrunner** [comment]
In SPL a final marker would not be sent in the case of a DirectoryScan followed by a FileSource operatror, because the directory scanner never terminates. The FileSource sends out a window marker after each file.

With the Java Application API, again with the directoryWatcher there is no end to the stream, so there graph will never terminate. If a graph terminates due to no more data from the sources, then the functional logic can implement AutoCloseable, which will be called upon termination.

textFileReader doesn't provide any indication of end of file, probably the best approach is to write your own multiTransform function that takes the file name from directoryWatcher and produces an object that contains lines or indicated end of file.

**Comment by hqingshuang** [comment]
@ddebrunner thanks for your comment.

**Comment by hildrum** [comment]
I can point you to an example that does what @ddebrunner mentions--in my initial experimentation version of [an hdfs file reader](https://github.com/hildrum/streamsx.topology.samples/blob/master/ReadFromHDFS/src/hdfshelper/HDFSFileReadIterator.java#L67) I send the String "done" to mean the file is over.  Then, where I was using the results of the file reader, I did special checking for the string "done".  

This might give you an idea of how to build what you want to, but I don't recommend copying that approach directly, as I can imagine "done" being a valid file line in some cases. I took the done marker out of the [final version](https://github.com/IBMStreams/samples/tree/master/JavaTopology/ReadFromHdfs) of that HDFSFileReader.
