### ISSUE TITLE
Python Primitive Operator in Fused Parallel Region Strange Behavior

### ISSUE THREAD

**Issue by bmwilli** [IBMStreams/streamsx.topology#2099]
I am using topology toolkit (version 1.10.3) that comes with IBM Streams 4.3.0.2.

I created a primitive operator using python that reads from elasticsearch.

The operator is used in a parallel region and the running width of the region = 2.

If I run each region in its own PE, everything works fine.

If I run with both regions fused into a single PE, this is where the fun begins:

In the elasticsearch index there are 621 documents. When looking at streams studio one of the operators reports it read 611 documents and the other reported 10.  I would have anticipated that they each red all 621 documents.

Both copies should be periodically scanning the index for updates.  I have a metric that counts total scans.  While it is running, only one of them is increasing its scan counter.

Is there any way that there is really only 1 copy of the python code running, and being shared by what streams has as two operators?

Thanks,
Brian

**Comment by ddebrunner** [comment]
Python VM is effectively single threaded, at least there is a Global lock (the GIL) that limits a single thread to be active in the Python VM at any time, so that might be having an effect. When fusing there is a single Python VM per PE with Python operators.

For that reason when topology has a parallel region it forces the region's channels not to fuse so that each channel will not interfere in an other due to the GIL.

It's also possible the elastic search library was not designed for multiple running instances at the same time.

Without having access to the code it's hard to know what could be happening.

**Comment by ddebrunner** [comment]
Note that C-extensions typically release the GIL when they are not directly interacting with the Python VM (through the Python C API), so that for example when issuing a system call that might block the GIL would be released. Standard Python libraries release the GIL at such points, e.g. `time.sleep()` releases the GIL before sleeping to allow other threads access to the VM (through the GIL).

Also Python releases the GIL periodically when executing Python byte code to allow thread switching.

**Comment by bmwilli** [comment]
Thanks Dan.  That helps understand the background of what might be going on.  I will attempt to recreate the issue such that I can share it.

**Comment by bmwilli** [comment]
The issue was a class variable that should have been an instance variable within my python class.
