### ISSUE TITLE
Group schema conversion operator with Publish

### ISSUE THREAD

**Issue by queeniema** [IBMStreams/streamsx.topology#2161]
Example: [Streams-RollingAverageSample.ipynb](https://github.com/IBMStreams/sample.starter_notebooks/blob/master/Streams-RollingAverageSample.ipynb) starter notebook

```python
def main():
  topo = Topology("SensorAverages", namespace="pythonSample")
  readings = topo.source(SensorReadingsSource(), name="Readings")
  valid_readings = readings.filter(lambda x : x["value"] > 100, name="ValidReadings")
  interval = timedelta(seconds=30)
  window = valid_readings.last(size=interval).trigger(when=timedelta(seconds=1))
  rolling_average = window.aggregate(average_reading).flat_map()
  averages_view = rolling_average.view(name="RollingAverage", description="Sample of rolling averages for each sensor")
  rolling_average.publish(topic="AverageReadings", schema=json, name="PublishAverage")
  context.submit("BUNDLE", topo, cfg)
```

The `publish` is publishing as a stream of JSON objects (`schema=json`):

```python
rolling_average.publish(topic="AverageReadings", schema=json, name="PublishAverage")
```

The logical graph looks like this:

![Screen Shot 2019-07-12 at 10 52 39 AM](https://user-images.githubusercontent.com/2454818/61148255-33570700-a493-11e9-978b-584ddec8ee0e.png)

The `as_json` operator is a standalone operator even though it is being defined as part of the `publish`. The graph would better map with the source if `as_json` was grouped into the `PublishAverage` operator.

**Comment by ddebrunner** [comment]
@queeniema  Here's what the change looks like with the console (new graph lower):
![image](https://user-images.githubusercontent.com/3769612/61152033-3acede00-a49c-11e9-96fb-2efc4a963316.png)

**Comment by ddebrunner** [comment]
@queeniema I'm not sure about this change. The issue is that the stream going into the `publish` has a schema (say `tuple<rstring id, int64 ts, float64 value>`) different to that being published (JSON) but from the graph there's no way to tell.

Thus a developer trying to subscribe to the stream would be assume the input stream to the publish would be needed by their application, not JSON.

The other viewpoint to not grouping in this case is that the conversion to JSON is explicit from `schema=json` so should be an explicit element in the graph.
