### ISSUE TITLE
Python API - support for parameters in user defined functions

### ISSUE THREAD

**Issue by henrychi2** [IBMStreams/streamsx.topology#276]
It seems we can't have parameters in user defined functions for operators like filter().  For example, we have a testcase like
hwf = hw.filter(test_functions.filter);
where filter(t) is
return "Wor" in t;

How do we do something like filter(t, x), so we can filter t whose length > x?  I'm curious if this is a known limitation.

**Comment by wmarshall484** [comment]
This is a known issue. 

There are some lingering issues with state handling in our use of python functions. The way it works right now, the primitive SPL operator is passed the location of a module and a function; we do not serialize functions. If multiple operators use the same function, then they'll share any state which is part of the function (i.e., global variables). At runtime, the primitive SPL operator discovers the function and invokes it when a tuple is received (passing it the tuple), and there is no initialization step.

As such, one way of enabling the users to pass parameters to the function, as things currently are, would involve passing them on every function call. For example:

``` Python
# Let's say we have a filter function in test_functions.py
# It takes three parameters: the tuple, and two threshold parameters
def filter(tuple, upper, lower):
    if tuple > lower and tuple < upper:
        return true
    return false
```

In Main.py, we'd have something like:

``` Python
top = Topology("someTopology")
# returns 1,2,3,4,...
stream1 = top.source(tupleCount())

# upper and lower will be passed to test_functions.filter on every invocation
lower = 11
upper = 99
stream2 = stream1.filter(test_functions.filter, upper, lower)
```

This way, upper and lower are passed to test_functions.filter on every invocation, when a tuple arrives. Implementing this would require adding filter/transform/source/sink parameters as another 'param' in the SPL primitive operator. For example, we could add a 'functionParameters' param to the SPL:

```
stream<int32 numbers> filtered = com.ibm.streamsx.topology.functional.python::PyFunctionFilter(inputStream){
param 
          functionModule : "test_functions",
          functionName : "filter",
          functionParameters : ["11", "99"];
}
```

The above is one way of solving the user-supplied parameter issue, but there's a better way -- we allow the user to pass callable classes to functions like filter() and transform(). In Python, any class which implements the __call__ field, is callable. The constructor of the class serves as initialization, and the user can use the class fields to persist state between invocations of __call__. Using callable class objects to do filtering also eliminates the issue with shared state between different operators.

 To do this, we'd need to serialize classes using pickle, and pass them as parameters to the SPL primitive operator. For example:

``` Python
# If we have a class which performs a filter operation, and takes two parameters
class filterUpperAndLower:
    def __init__(self, upper, lower ):
        self.upper = upper 
        self.lower = lower 
    def __call__(self, tuple):
        if tuple > self.lower and tuple < self.upper :
            return true
        return false
```

Then, in Main.py:

``` Python
top = Topology("someTopology")
# returns 1,2,3,4,...
stream1 = top.source(tupleCount())

# upper and lower will be used to create a new filterUpperAndLower object
lower = 11
upper = 99
stream2 = stream1.filter( filterUpperAndLower(upper, lower) )
```

In the SPL primitive operator, we would pass the entire serialized class as a parameter, as well as its location and definition, and then deserialize it upon operator start up:

```
stream<int32 numbers> filtered = com.ibm.streamsx.topology.functional.python::PyFunctionFilter(inputStream){
param 
          functionModule : "test_functions",
          className : "filterUpperAndLower",
          serializedClass : "(i__main__\nfilterUpperAndLower\np0\n(dp1\nS'upper'\np2\nI11\nsS'lower'\np3\nI99\nsb.";
}
```

This way, you can pass parameters to the class on creation, and the class will contain its own state which is a much needed component that is missing from our API. Since callable class serialization is similar to how the Java Application API handles state, I think it would be a good bet for the Python API.

**Comment by ddebrunner** [comment]
By 'serialize class', is it actually serialize an instance of the class?

**Comment by wmarshall484** [comment]
Yes, an instance of the class is serialized. It is still necessary to keep track of the module and class name, and it will need to be imported by the python runtime to deserialize it in the SPL primitive operator. 

Just to be totally clear, here's an example of pickling (serializing) an instance of a class:
``` Python
>>> class filterUpperAndLower:
...     def __init__(self, upper, lower ):
...             self.upper = upper
...             self.lower = lower
...     def __call__(self, tuple):
...             if tuple > self.lower and tuple < self.upper :
...                     return true
...             return false
...
>>> pickle.dumps(filterUpperAndLower(11,99) )
"(i__main__\nfilterUpperAndLower\np0\n(dp1\nS'upper'\np2\nI11\nsS'lower'\np3\nI99\nsb."
```

**Comment by henrychi2** [comment]
Support for stateful operators using instances of callable classes has been added.
