### ISSUE TITLE
Remove PyFunctionPassThru operator

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.topology#329]
* it's not a functional operator as it doesn't call a function 
* it's not needed, just use `spl.relational::Filter` from the standard toolkit.

**Comment by drhvm** [comment]
Filter has the added overhead of calling into Python whereas it is not needed in this case.  The PyFunctionPassThru could also be used instead of the PyFunctionHashRemover again vs. Filter suggestion.  Is it worth keeping around for these 2 purposes or is the overhead to call into python module negligible?

**Comment by ddebrunner** [comment]
Not the Python filter, but `spl.relational::Filter`, it knows nothing about Python.
