### ISSUE TITLE
[Python] Support Anaconda

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.topology#383]
https://www.continuum.io/why-anaconda

**Comment by ddebrunner** [comment]
I downloaded Ananconda 3.5 to a clean Streams VM (that did not already have Python 3.5 installed).

I installed Anaconda by running the downlaoded script and accepting the defaults for everything.
https://www.continuum.io/downloads

This results in Ananconda being installed in `$HOME/anaconda3` and Anaconda being PATH.

Then standalone applications worked,  e.g. from the samples.

`python3 hello_world.py`

To get distributed running I had to set the Application Environment variable PYTHONHOME for my Streams instance to the location of Anaconda. Eg. this is the console view of my setting:

![image](https://cloud.githubusercontent.com/assets/3769612/15402654/3c872f12-1daa-11e6-83d4-c7903d645fe1.png)

Not sure if this requires a restart of the instance.

**Comment by sdickes** [comment]
On a system with Anaconda, Streams, and the latest version of the topology toolkit installed we built the hello world sample. 
PYTHONHOME was appropriately set as an application-ev and the test application ran fine.

We copied the hello world SAB file to a test system with Anaconda, and Streams installed. 
PYTHONHOME was appropriately set as an application-ev but the test application did not work and failed with an error during operator loading that the python library could not be found. 
We set LD_LIBRARY_PATH=$HOME/anaconda3/lib as an applicaiton-ev and then the sample application ran fine. 

We are not sure at this point why nor if setting LD_LIBRARY_PATH is a valid means of running the instance application.

**Comment by wmarshall484** [comment]
The LD_LIBRARY_PATH might have something to do with the call to dlopen in loadCPython(), which is necessary to allow for the usage of third party CPython libraries:
https://github.com/IBMStreams/streamsx.topology/blob/master/com.ibm.streamsx.topology/opt/python/include/splpy.h

I say *possible* because LD_LIBRARY_PATH doesn't need to be set when not using Anaconda, but the error message is in line with a call to dlopen() failing.

**Comment by sdickes** [comment]
Seeing the original error led us to try the LD_LIBRARY_PATH setting -- with good results but no explanation at this point. @drhvm

**Comment by ddebrunner** [comment]
@sdickes Was the Anaconda install location different on the two systems you tested?

**Comment by ddebrunner** [comment]
@wmarshall484 Should the code in loadCPython() use PYTHONHOME to locate the dll?

**Comment by ddebrunner** [comment]
Does pull request #417 help?

**Comment by ddebrunner** [comment]
I tested pr #417 by creating a sab file using an Anaconda distribution in /tmp and then removed it before submitting the bundle. The jar continued to pick up the /usr/lib python rather than anaconda the instance is using with PYTHONHOME set.

**Comment by ddebrunner** [comment]
So we need these set as application environment variables in the Streams instance:

* PYTHONHOME set to the location of Anaconda
* LD_LIBRARY_PATH to include $PYTHONHOME/lib

Note that LD_LIBRARY_PATH must have the expanded version of $PYTHONHOME/lib

**Comment by ibmkendrick** [comment]
dlopen() finds share libraries using the standard ld search order: (info taken from https://en.wikipedia.org/wiki/Rpath)
* LD_PRELOAD or /etc/etc/ld.so.preload
* rpath in executable
* LD_LIBRARY_PATH
* /etc/ld.so.conf

rpath is a better mechanism for locating libraries because it is specified within each executables/shared libraries.  Using LD_LIBRARY_PATH would work too, but it has its disadvantages, especially when the folder contains libraries that conflicts with the system libraries, as is in the case of /anaconda/lib.

Here is a test to show how rpath works:
* main() calling operator() in lib2/liboperator.so
* operator() loading lib1/libfoo.so via dlopen.
* both main() and operator() contains rpath to locate the needed libraries.

main.c:
```c
#include <stdio.h>
extern void operator(void);

int main ()
{
  printf ("I'm in main.\n");
  operator();
  return 0;
}
```

operator.c:
```c
#include <stdio.h>
#include <dlfcn.h>

void (* foo_handle)(void);

int operator ()
{
  printf ("I'm in operator()\n");
  void* handle = dlopen("libfoo.so", RTLD_LAZY | RTLD_GLOBAL);

  if (!handle) {
    printf ("Error loading libfoo.so\n");
    return -1;
  }

  foo_handle = dlsym(handle, "foo");
  foo_handle();
  return 0;
}
```

foo.c:
```c
#include <stdio.h>

void foo(void)
{
  printf ("I'm share library libfoo.so\n");
}
```

Compile commands:
```
gcc -shared -fpic foo.c -o libfoo.so
gcc -shared -fpic -ldl -Wl,-rpath,'$ORIGIN/../lib1' operator.c -o liboperator.so
gcc -L. -loperator -Wl,-rpath,'$ORIGIN/lib2' main.c -o main 

rm -rf lib1 lib2
mkdir -p lib1 lib2
mv libfoo.so lib1/
mv liboperator.so lib2/
```

To run:
```
unset LD_LIBRARY_PATH
./main
```

Expected output:
```
I'm in main.
I'm in operator()
I'm share library libfoo.so
```

**Comment by ddebrunner** [comment]
but rpath only helps if you know where the library will be, right.

**Comment by ibmkendrick** [comment]
Yes, I also tried loading it via absolute path:

```c
#include <stdio.h>
#include <stdlib.h>
#include <dlfcn.h>

void (* foo_handle)(void);

int operator ()
{
  printf ("I'm in operator()\n");

  char* foopath = getenv("FOOPATH");
  if (!foopath) {
    printf ("Must set FOOPATH to location of libfoo.so\n");
    return -1;
  } else {
    printf ("FOOPATH=%s\n", foopath);
  }


  char path[256];
  sprintf(path, "%s/libfoo.so", foopath); 
  void* handle = dlopen(path, RTLD_LAZY | RTLD_GLOBAL);
  if (!handle) {
    printf ("Error loading libfoo.so\n");
    return -1;
  }

  foo_handle = dlsym(handle, "foo");
  foo_handle();
  return 0;
}
```

And things seems to work without LD_LIBRARY_PATH as well.

**Comment by ibmkendrick** [comment]
rpath can be modified after the executables/shared libraries are created.  For example, the runtime can use the value of PYTHONHOME and correct rpath to match the runtime environment.

Having said that, the current logic in topology of using absolute path should work as well.

**Comment by ibmkendrick** [comment]
Here is an attempt to explain why the explicit absolute loading didn't work...

I looked at one of the operator in the SAB:
```
$ readelf -d tweets_0.so

Dynamic section at offset 0x19c80 contains 36 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libpython3.5m.so.1.0]
 0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
...
```

I noticed that `libpython3.5m.so.1.0` is needed, which would effectively render the dlopen() logic useless, because runtime would try to find the library before even trying to execute the code.

so if the operator model doesn't specify <cmn:lib/>, then I think the dlopen() logic would kick in.

**Comment by ddebrunner** [comment]
Anaconda is supported.
