### ISSUE TITLE
Question: Using topology to make toolkits?

### ISSUE THREAD

**Issue by ecurtin** [IBMStreams/streamsx.topology#419]
Howdy,

Is it possible to write toolkits using topology that could be plugged into a more traditional SPL development environment in Streams Studio? If so, what does that workflow look like?

**Comment by ddebrunner** [comment]
Not yet, it is something that has been thought about.

Basically build composites in Python/Java/Scala that then can be called from SPL.

**Comment by chanskw** [comment]
I am thinking about the same thing too.  I need to design a toolkit using the topology API that can be integrated with other existing SPL applications.

My current thinking is that I would write a more "reusable" application using the topology APIs and export data from the application for downstream applications to consume.  The topology application will serve some specific functions in a bigger application.

**Comment by ddebrunner** [comment]
Another approach is the microservice approach, where "micro-applications" are connected together using publish-subscribe. So an SPL application can publish a stream that is consumed by a Python App  that publishes a stream that is consumed by a Java app and an SPL app etc. etc.

Thus one breaks functionality into applications rather than SPL composites.

**Comment by ddebrunner** [comment]
Requires #394 to be fixed
