### ISSUE TITLE
Calling SPL operators from Python applications

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.topology#483]
I can't seem to find this from the documentation.  In the Python Topology API, can we invoke an operator from one of the existing toolkits (e.g. time series?)

**Comment by ddebrunner** [comment]
I have some experimental code running, it looks like this for a DirectoryScan feeding a FileSource and then into a Python function:

```
    files = spl_ops.source("spl.adapter::DirectoryScan", topology=topo,
          schema=CommonSchema.String, params = {'directory': '/tmp/work'})

    lines = spl_ops.map("spl.adapter::FileSource", files)

    lines = lines.map(string.capwords)

```

There's also a general purpose `spl_ops.invoke(...)` which handles an arbitrary number of input and output ports.

The main issue seems to handling parameters, since SPL has strict typing and Python doesn't. E..g the need to pass a `int32` parameter value as `'iterations': int32(4)` rather than just `'iterations': 4` for a Beacon.

**Comment by ddebrunner** [comment]
Here's the same example, with a different import that removes the need for spl_ops:

```
    # Invoke an SPL DirectoryScan operator as a source.
    # This one scans /tmp/work for files.
    # Note the full kind of the operator is required.
    files = source("spl.adapter::DirectoryScan", topology=topo,
        schema=CommonSchema.String, params = {'directory': '/tmp/work'})

    # Follow it with a FileSource operator
    # If no schema is provided to map then the input
    # schema is used.
    lines = map("spl.adapter::FileSource", files)

    # Feed the lines into a Python function
    lines = lines.map(string.capwords)

```

**Comment by ddebrunner** [comment]
Working code in pr #499

**Comment by ddebrunner** [comment]
Added though api has changed to be class based instead of function to allow output clauses.
