### ISSUE TITLE
Can we change TStream.unparallel to TStream.merge?

### ISSUE THREAD

**Issue by scotts** [IBMStreams/streamsx.topology#63]
Or perhaps `TStream.mergeParallel`? That may imply that the parallel side should then be `TStream.splitParallel`, but I prefer the simplicity of `TStream.parallel` and `TStream.merge`.

"unparallel" reads strange to me. I think that positive names ("do this" -> "merge this") tend to be more clear on their semantics than negative names ("undo that" -> "un-parallel that").

**Comment by ddebrunner** [comment]
Makes sense.

**Comment by ddebrunner** [comment]
Thinking about this more, and based upon some other feedback parallel/merge are not obviously related, so i wonder if we should use the more logical:

partition(...)  - // Partition a stream
merge() // Merge a partitioned stream

The fact that under the covers its SPL's UDP is just an implementation detail.

**Comment by hildrum** [comment]
I think `partition` could be confusing.    Partition to me suggests dividing the stream up on some key.   Moreover, when I partition on that key, my expectation is that it is as if each of those keys has its own stream.   (This is not true in SPL, and I have to keep reminding myself of that fact.)  Maybe this is just SPL's influence, though, and new users wouldn't think this way.  

What about `split` or `separate` instead of `parallel`?

**Comment by ddebrunner** [comment]
I think split should be kept for the SPL Split operator style functionality, split for different streams with probable different processing on each stream. I'm thinking of adding a split method, something like:

split(ToIntFunction<T> indexer)

**Comment by ddebrunner** [comment]
Moving to the next milestone to give time to decide on names.

**Comment by wmarshall484** [comment]
I took a look at the parallel naming scheme for Java8's Stream interface -- Java8 uses parallel() and sequential(). This is because Java8's Stream uses a different kind of parallelism than we employ:
*"Streams facilitate parallel execution by reframing the computation as a pipeline of aggregate operations, rather than as imperative operations on each individual element."*

I think what it's getting at is that Java8's uses per-tuple processing by default, and does batching+parallel processing on the batch elements when .parallel() is invoked. Per-tuple processing is resumed when .sequential() is called.

As such, we should NOT use Java8's naming scheme; they use different kinds of parallelism.

**Comment by scotts** [comment]
Yes, although we can map their names to ours. Java 8's "sequential" maps to our "lowlatency", and there is no mapping for "parallel" because we plan on injecting threaded ports by default.

In other words, Java 8's parallel implicitly means pipeline parallelism. Our parallel implicitly means data parallelism, and we have pipeline parallelism turned on by default. (Or that's my current understanding of the plan.)

**Comment by scotts** [comment]
If we don't like `merge` or `mergeParallel`, how about `endparallel` or `endParallel`?

**Comment by ddebrunner** [comment]
endParallel() matches endLowLatency()
