### ISSUE TITLE
Support .isolate(), .lowLatency(), and .endLowLatency() methods.

### ISSUE THREAD

**Issue by wmarshall484** [IBMStreams/streamsx.topology#70]
Currently, if a streams application is submitted with some form of a DISTRIBUTED context, the default is to run each operator in a separate PE. This is also the default for SPL programs, and has caused issues where customers create an excessive number of processes on their systems.

With the Java Application API, we are going to change the default behavior -- by default, every operator will run in the same PE, separated by threaded ports. 

If a Java Application API developers wants to separate subsequent operations into a separate PE they can call .isolate(), which returns a reference to a TStream whose child streams will run in a separate PE. To put this in SPL terms, everything runs in the same partition colocation by default; calling .isolate() creates another partition colocation in which the TStream's children run.

Lastly, introducing threaded ports between each operator incurs higher latency, so there will be a second mode of processing called "low latency". Low latency processing indicates that all operators will be created on the same PE <b>without</b> threaded ports between each other. Low latency processing can be started by calling a "lowLatency()" method on a TStream. This returns a reference to a TStream whose child operations will not be separated by threaded ports. Default processing may be resumed by calling an "endLowLatency()" method on a child TStream.

To reiterate: there are going to be three methods added to TStream:
.lowLatency()
.endLowLatency()
.isolate()

There will be two types of processing:
default - in which every operation (transformation, filtering, ...) is on the same PE, separated by threaded ports.
low latency - in which every operation is on the same PE, but are not separated by threaded ports.

**Comment by hildrum** [comment]
If the threaded port is implemented in the C++-layer,  I think `lowLatency` and `endLowLatency` are probably not good names.  At least for large tuples, the most noticeable effect of sticking a threaded port before every operator is going to be higher CPU usage and lower overall throughput.   A user concerned about throughput may not consider a method with the name `lowLatency` is the opposite of what they want to do.
I think a name that implied merging or combining would be a better one--`merge` is already in use, but `consolidate`, `fuse`, `meld`, `compound`?

**Comment by ddebrunner** [comment]
Doesn't it depend on what is downstream of the threaded port? With a complex function  (say image processing ) a threaded port is likely to increase throughput regardless of tuple size.

**Comment by hildrum** [comment]
Yes, it depends on the application.  Threaded ports can definitely make a huge difference.  However,  given the set of defaults you've chosen, eliminating threaded ports will likely improve performance when tuples are large, since it takes what would have been at least one copy into a call by reference.  (If you have a different threaded port implementation planned, then this may not apply.)  

If all your transforms are heavy-weight, then the copying will be worth it to get the pipeline parallelism.   But if you have some transforms that are lightweight, you'll want to eliminate the threaded port before or after them, and I don't think `lowLatency` is the name they'll be looking for.   I'm not sure what a good name is; a couple of other suggestions are `link` or `tie`.
