### ISSUE TITLE
Determine use of all credential environment variables.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.topology#920]
We have:
`VCAP_SERVICES`, `STREAMING_ANALYTICS_SERVICE_NAME`, `STREAMS_USER` (?), `STREAMS_PASSWORD`.

Also `STREAMS_DOMAIN_ID`, `STREAMS_INSTANCE_ID` but they are used as expected for Streams on-prem.

Need to understand fully how these are used in submit, tester and connections.

@ibmkendrick

**Comment by jakrmpotic** [comment]
@ddebrunner Some feedback from Stacy: the term "VCAP_SERVICES" confused her. Can we just use CREDENTIALS? That would match what she sees on Bluemix (the term VCAP_SERVICES seems to be obsolete or only used in older docs).

**Comment by ibmkendrick** [comment]
@jakrmpotic , `VCAP_SERVICES` is an environment provided by Bluemix to interact with its services. See: https://console.ng.bluemix.net/docs/cli/vcapsvc.html

**Comment by jakrmpotic** [comment]
I was hoping the CLI matched the new GUI (attached) which doesn't mention VCAP_SERVICES at all. Since we're pointing users to the GUI to get their credentials, we need to document how that equates to VCAP_SERVICES. I guess the blurb I added to our notebook isn't sufficient yet (or the user just skims the content and misses the association). I will work on the wording. 
<img width="1482" alt="screen shot 2017-03-22 at 11 48 05 am" src="https://cloud.githubusercontent.com/assets/24479385/24215395/e04066cc-0ef5-11e7-9b76-c204f53fd464.png">

**Comment by ibmkendrick** [comment]
`VCAP_SERVICES` may contain one or more of the credentials listed in the GUI.  And it may even include other services like IOT platform, for example.  The `VCAP_SERVICES` has the format of:
```
{
  "streaming-analytics": [ 
    { "name": "Credentials-1", "credentials": { ... } },
    { "name": "Credentials-2", "credentials": { ... } }
  ]
}
```

**Comment by ibmkendrick** [comment]
## Tester
###  DISTRIBUTED:
* username: (first option wins, if specified)
   1. Tester.test(username=xxx)
   1. env['STREAMS_USERNAME']
   1. "streamsadmin"
* password:
   1. Tester.test(password=xxx)
   1. env['STREAMS_PASSWORD']
   1. "passw0rd"

###  STREAMING_ANALYTICS:
*note*: If using Tester.setup_streaming_analytics(), env['VCAP_SERVICES'] must be present

* vcap:
   1. Tester.test(config={'topology.service.vcap': xxx})
   1. env['VCAP_SERVICES']
* service_name:
   1. Tester.test(config={'topology.service.name': xxx })
   1. Tester.setup_streaming_analytics(service_name=xxx)
   1. env['STREAMING_ANALYTICS_SERVICE_NAME']

## REST Connection
### StreamsConnection:
* username:
   1. StreamsConnection(username=xxx)
   1. "streamsadmin" if env['STREAMS_INSTALL']
* password:
   1. StreamsConnection(password=xxx)
   1. "passw0rd" if env['STREAMS_INSTALL']

### StreamingAnalyticsConnection:
* vcap:
   1. StreamingAnalyticsConnection(vcap_services: xxx)
   1. env['VCAP_SERVICES']
* service_name:
   1. StreamingAnalyticsConnection(service_name: xxx)
   1. env['STREAMING_ANALYTICS_SERVICE_NAME']

## context.submit()
### DISTRIBUTED
uses StreamsConnection object in config, otherwise, creates one using:
* username:
   1. submit(username=xxx)
* password:
   1. submit(password=xxx)

###  ANALYTICS_SERVICE
use StreamingAnalyticsConnection object in config, otherwise, creates one using:
* vcap:
   1. submit(config={'topology.service.vcap': xxx})
* service_name:
   1. submit(config={'topology.service.name': xxx})

*note*: For actual job submission, it uses:
* config={'topology.service.vcap': xxx} or env['VCAP_SERVICES']
* config={'topology.service.name': xxx}
* it does not use StreamsConnection object in config even if it's provided (See #921)

**Comment by ibmkendrick** [comment]
Notable observations:
1. StreamsConnection does not make use of `STREAMS_USERNAME` nor `STREAMS_PASSWORD`
1. submit('ANALYTICS_SERVICE') does not make use of `STREAMING_ANALYTICS_SERVICE_NAME`.
